export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";
export const ADD_NOTIFICATION = `ADD_NOTIFICATION`;

export const ADD_NEW_NOTIFICATION = `ADD_NEW_NOTIFICATION`;
export const EMPTY_NOTIFICATIONS = `EMPTY_NOTIFICATIONS`;
